#!/usr/bin/env python3
"""Generate the catalog and the category browsing indexes from contribution metadata.

Writes:
  catalog/mlu-contributions.json   full records, for tooling
  catalog/mlu-contributions.csv    flat inventory, for download
  mlu/<category>/README.md         the browsable index table for each category
  collections/README.md            the curated-list index
  README.md                        the category table, inside its GENERATED markers

Everything here is derived. Edit mlu-contribution.yml, not the output.

A contribution whose github.download_url is null is listed as "not yet released" rather than
given a download link, so the catalog never advertises a package that does not exist.

Usage:  python3 scripts/build_catalog.py [--check]
        --check exits non-zero if any generated file is out of date, without writing.
"""
from __future__ import annotations

import csv
import io
import json
import sys
from datetime import date
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "catalog"
REPO_URL = "https://github.com/DTC-Consortium/DTC-Consortium-MLU"

GENERATED = "<!-- Generated by scripts/build_catalog.py. Do not edit by hand. -->"

CATEGORY_INTROS = {
    "course-elements": (
        "Course Elements",
        "Courses, credentials, modules, lectures, assignments, assessments, and instructional\n"
        "materials contributed by the DTCC faculty community.",
    ),
    "ml-ai-applications": (
        "ML/AI Applications",
        "Prompts, applications, codebases, datasets, tool flows, and platforms. Everything here is\n"
        "a working tool — check each contribution's README for what it does and does not decide\n"
        "on its own.",
    ),
    "professional-student-development": (
        "Professional and Student Development",
        "Bootcamps, workshops, training, presentations, and related initiatives, for faculty and\n"
        "for students.",
    ),
}


def load() -> list[dict]:
    docs = []
    for path in sorted(ROOT.glob("mlu/*/*/mlu-contribution.yml")):
        doc = yaml.safe_load(path.read_text(encoding="utf-8"))
        doc["_dir"] = str(path.parent.relative_to(ROOT))
        docs.append(doc)
    return sorted(docs, key=lambda d: d["id"])


def download_cell(doc: dict) -> str:
    """A download link only when the release asset actually exists."""
    url = doc["github"].get("download_url")
    if not url:
        return "_not yet released_"
    return f"[`v{doc['version']}`]({url})"


def category_index(cat: str, docs: list[dict]) -> str:
    title, intro = CATEGORY_INTROS[cat]
    rows = [d for d in docs if d["category"] == cat]
    out = [f"# {title}", "", GENERATED, "", intro, ""]
    if not rows:
        out += [
            "**No contributions have been published in this category yet.**",
            "",
            f"See [`MLU-CONTRIBUTING.md`]({'../../MLU-CONTRIBUTING.md'}) to submit the first one, or",
            f"[`templates/{cat}/`](../../templates/{cat}) for the starting layout.",
            "",
        ]
        return "\n".join(out)

    out += [
        f"**{len(rows)} contribution{'s' if len(rows) != 1 else ''}.**",
        "",
        "| Title | Summary | Institution | Tools | Audience | Version | Download |",
        "|---|---|---|---|---|---|---|",
    ]
    for d in rows:
        name = Path(d["_dir"]).name
        summary = " ".join(d["summary"].split())
        if len(summary) > 180:
            summary = summary[:177].rsplit(" ", 1)[0] + "…"
        maturity = "" if d["maturity"] == "classroom-tested" else " _(pilot)_"
        out.append(
            f"| [**{d['title']}**]({name}) <br>`{d['id']}`{maturity} "
            f"| {summary} "
            f"| {', '.join(d['institutions'])} "
            f"| {', '.join(d['tools'][:4])}{'…' if len(d['tools']) > 4 else ''} "
            f"| {', '.join(d['audience'])} "
            f"| {d['version']} "
            f"| {download_cell(d)} |"
        )
    out += [
        "",
        "Download links point at a version-specific release asset. `not yet released` means the",
        "materials are browsable here but no package has been published for them yet — see",
        "[Downloading a contribution](../../README.md#downloading-a-contribution).",
        "",
    ]
    return "\n".join(out)


def collections_index(docs: list[dict]) -> str:
    by_id = {d["id"]: d for d in docs}
    out = [
        "# Collections",
        "",
        GENERATED,
        "",
        "Curated lists that group published contributions by cohort, institution, course kit, or",
        "event. A collection never holds materials of its own — it points at contributions that",
        "each live in exactly one canonical place.",
        "",
        "To propose one, open a pull request adding a `<id>.yml` file here. See",
        "[`../docs/maintenance.md`](../docs/maintenance.md).",
        "",
    ]
    files = sorted(ROOT.glob("collections/*.yml"))
    if not files:
        out += ["**No collections yet.**", ""]
        return "\n".join(out)
    for f in files:
        c = yaml.safe_load(f.read_text(encoding="utf-8"))
        out += [
            f"## {c['title']}",
            "",
            f"`{c['id']}` · {c['kind']}" + (f" · {c['cohort']}" if c.get("cohort") else ""),
            "",
            " ".join(c["summary"].split()),
            "",
            "| # | Contribution | Why it is here |",
            "|---:|---|---|",
        ]
        for m in sorted(c["members"], key=lambda m: m["order"]):
            d = by_id.get(m["id"])
            if d is None:
                out.append(f"| {m['order']} | `{m['id']}` — **missing** | {m.get('note', '')} |")
                continue
            rel = f"../{d['_dir']}"
            out.append(f"| {m['order']} | [{d['title']}]({rel}) <br>`{d['id']}` | {m.get('note', '')} |")
        out.append("")
    return "\n".join(out)


def root_category_table(docs: list[dict]) -> str:
    """The category table inside the marked block in the root README."""
    lines = [
        "| Category | What lives there | Published |",
        "|---|---|---|",
    ]
    for cat, (title, _) in CATEGORY_INTROS.items():
        rows = [d for d in docs if d["category"] == cat]
        blurb = {
            "course-elements": "Courses, credentials, modules, lectures, assignments, assessments, instructional materials",
            "ml-ai-applications": "Prompts, applications, codebases, datasets, tool flows, platforms",
            "professional-student-development": "Bootcamps, workshops, training, presentations, related initiatives",
        }[cat]
        count = f"**{len(rows)}**" if rows else "_none yet_"
        lines.append(f"| **[{title}](mlu/{cat})** | {blurb} | {count} |")
    return "\n".join(lines)


def splice(text: str, name: str, block: str) -> str:
    begin, end = f"<!-- BEGIN GENERATED: {name} -->", f"<!-- END GENERATED: {name} -->"
    i, j = text.index(begin), text.index(end)
    return text[: i + len(begin)] + "\n" + block + "\n" + text[j:]


def build_json(docs: list[dict]) -> str:
    records = []
    for d in docs:
        rec = {k: v for k, v in d.items() if not k.startswith("_")}
        rec["browse_url"] = f"{REPO_URL}/tree/main/{d['_dir']}"
        rec["released"] = bool(d["github"].get("download_url"))
        records.append(rec)
    payload = {
        "generated": date.today().isoformat(),
        "repository": REPO_URL,
        "schema": "schemas/mlu-contribution.schema.json",
        "count": len(records),
        "contributions": records,
    }
    return json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=False) + "\n"


CSV_COLUMNS = [
    "id", "title", "category", "subtype", "summary", "authors", "institutions",
    "disciplines", "tools", "audience", "difficulty", "duration", "delivery_format",
    "language", "maturity", "version", "published", "last_reviewed",
    "content_license", "software_license", "cohort", "collection_ids",
    "browse_url", "download_url", "released",
]


def build_csv(docs: list[dict]) -> str:
    buf = io.StringIO()
    w = csv.DictWriter(buf, fieldnames=CSV_COLUMNS, lineterminator="\n")
    w.writeheader()
    for d in docs:
        j = lambda v: "; ".join(v) if isinstance(v, list) else ("" if v is None else str(v))
        w.writerow({
            "id": d["id"], "title": d["title"], "category": d["category"], "subtype": d["subtype"],
            "summary": " ".join(d["summary"].split()),
            "authors": "; ".join(a["name"] for a in d["authors"]),
            "institutions": j(d["institutions"]), "disciplines": j(d["disciplines"]),
            "tools": j(d["tools"]), "audience": j(d["audience"]),
            "difficulty": j(d.get("difficulty")), "duration": j(d.get("duration")),
            "delivery_format": j(d.get("delivery_format")), "language": j(d.get("language")),
            "maturity": d["maturity"], "version": d["version"],
            "published": d["published"], "last_reviewed": d["last_reviewed"],
            "content_license": d["licenses"]["content"],
            "software_license": j(d["licenses"].get("software")),
            "cohort": j(d.get("cohort")), "collection_ids": j(d.get("collection_ids")),
            "browse_url": f"{REPO_URL}/tree/main/{d['_dir']}",
            "download_url": j(d["github"].get("download_url")),
            "released": "yes" if d["github"].get("download_url") else "no",
        })
    return buf.getvalue()


def main() -> int:
    check = "--check" in sys.argv
    docs = load()
    targets = {
        CATALOG / "mlu-contributions.json": build_json(docs),
        CATALOG / "mlu-contributions.csv": build_csv(docs),
        ROOT / "collections" / "README.md": collections_index(docs),
    }
    for cat in CATEGORY_INTROS:
        targets[ROOT / "mlu" / cat / "README.md"] = category_index(cat, docs)

    readme = ROOT / "README.md"
    targets[readme] = splice(readme.read_text(encoding="utf-8"), "category-table", root_category_table(docs))

    stale = []
    for path, text in targets.items():
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")

    if check:
        for s in stale:
            print(f"error: {s} is out of date; run scripts/build_catalog.py", file=sys.stderr)
        return 1 if stale else 0
    print(f"\n{len(docs)} contribution(s) catalogued.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
