#!/usr/bin/env python3
"""Generate CITATION.cff and LICENSE.md for each contribution from its metadata.

Both files restate facts that already live in mlu-contribution.yml, so they are
generated rather than hand-maintained. README.md and CHANGELOG.md are written by
the contributor and are never touched here.

Usage:  python3 scripts/generate_boilerplate.py [--check]
        --check exits non-zero if any generated file is out of date.
"""
from __future__ import annotations

import sys
import textwrap
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
REPO_URL = "https://github.com/DTC-Consortium/DTC-Consortium-MLU"

CC_BY_SUMMARY = """You may share and adapt this material for any purpose, including commercially,
provided you give appropriate credit, link to the licence, and indicate whether
changes were made. Full text: https://creativecommons.org/licenses/by/4.0/"""


def citation(doc: dict) -> str:
    lines = [
        "cff-version: 1.2.0",
        "message: If you use these materials, please cite them as below.",
        "type: dataset",
        f"title: {doc['title']!r}",
        f"version: {doc['version']}",
        f"date-released: {doc['published']}",
        f"license: {doc['licenses']['content']}",
        f"repository-code: {REPO_URL}",
        f"url: {REPO_URL}/tree/main/{doc['github']['path']}",
        f"abstract: >-",
    ]
    # A folded scalar turns every newline into a space, so wrap on word boundaries only.
    summary = " ".join(doc["summary"].split())
    lines.extend(f"  {line}" for line in textwrap.wrap(summary, width=88, break_on_hyphens=False, break_long_words=False))
    lines.append("authors:")
    for a in doc["authors"]:
        lines.append(f"  - name: {a['name']!r}")
        if a.get("institution"):
            lines.append(f"    affiliation: {a['institution']!r}")
        if a.get("orcid"):
            lines.append(f"    orcid: 'https://orcid.org/{a['orcid']}'")
    lines.append("keywords:")
    for k in doc["topics"]:
        lines.append(f"  - {k!r}")
    lines.append(f"identifiers:\n  - type: other\n    value: {doc['id']}\n    description: MLU contribution ID")
    return "\n".join(lines) + "\n"


def license_md(doc: dict) -> str:
    content = doc["licenses"]["content"]
    software = doc["licenses"].get("software")
    data = doc["licenses"].get("data") or []

    out = [
        f"# Licence — {doc['id']}",
        "",
        "<!-- Generated by scripts/generate_boilerplate.py from mlu-contribution.yml. Do not edit by hand. -->",
        "",
        "This contribution carries more than one licence. Check the row that covers the file you",
        "want to reuse before you reuse it.",
        "",
        "| What | Licence |",
        "|---|---|",
        f"| Documentation, instructional text, slides, and guides | `{content}` |",
    ]
    if software:
        out.append(f"| Code — notebooks, scripts, and helper modules | `{software}` |")
    if data:
        out.append("| Bundled sample data | per file, see the table below |")
    out += ["", f"Copyright (c) {doc['published'][:4]} " + ", ".join(doc["institutions"]) + ".", ""]

    out += [
        f"## Documentation and instructional material — {content}",
        "",
        CC_BY_SUMMARY,
        "",
        f"Attribute as: *{doc['title']}* ({doc['id']}), "
        + ", ".join(a["name"] for a in doc["authors"])
        + f", {', '.join(doc['institutions'])}. See `CITATION.cff`.",
        "",
    ]

    if software:
        out += [f"## Code — {software}", ""]
        if software == "MIT":
            holders = ", ".join(doc["institutions"])
            out += [
                f"Copyright (c) {doc['published'][:4]} {holders}",
                "",
                "Permission is hereby granted, free of charge, to any person obtaining a copy of this",
                "software and associated documentation files (the \"Software\"), to deal in the Software",
                "without restriction, including without limitation the rights to use, copy, modify, merge,",
                "publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons",
                "to whom the Software is furnished to do so, subject to the following conditions:",
                "",
                "The above copyright notice and this permission notice shall be included in all copies or",
                "substantial portions of the Software.",
                "",
                "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,",
                "INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR",
                "PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE",
                "FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR",
                "OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER",
                "DEALINGS IN THE SOFTWARE.",
                "",
            ]
        else:
            out += [
                f"The notebooks, scripts, and helper modules in this contribution are released under the "
                f"{software} licence. Its full text applies as published by its steward.",
                "",
            ]

    if data:
        out += [
            "## Bundled sample data",
            "",
            "Each bundled file keeps the licence of its source. Nothing here is a real student record.",
            "",
            "| File | Licence | Source |",
            "|---|---|---|",
        ]
        for d in data:
            src = " ".join(d["source"].split())
            out.append(f"| `{d['path']}` | `{d['license']}` | {src} |")
        out.append("")
        notes = [d for d in data if d.get("notes")]
        if notes:
            out.append("### Notes")
            out.append("")
            for d in notes:
                out.append(f"- **`{Path(d['path']).name}`** — {' '.join(d['notes'].split())}")
            out.append("")

    out += [
        "## What this licence does not cover",
        "",
        "No licence here is granted over material owned by AWS, by an institution, or by any other",
        "third party. Where such material is referenced, it is linked rather than redistributed.",
        "See [`../../../docs/licensing.md`](../../../docs/licensing.md).",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    check = "--check" in sys.argv
    stale: list[str] = []
    for path in sorted(ROOT.glob("mlu/*/*/mlu-contribution.yml")):
        doc = yaml.safe_load(path.read_text(encoding="utf-8"))
        for name, text in (("CITATION.cff", citation(doc)), ("LICENSE.md", license_md(doc))):
            target = path.parent / name
            if check:
                if not target.exists() or target.read_text(encoding="utf-8") != text:
                    stale.append(str(target.relative_to(ROOT)))
            else:
                target.write_text(text, encoding="utf-8")
                print(f"wrote {target.relative_to(ROOT)}")
    if check:
        for s in stale:
            print(f"error: {s} is out of date; run scripts/generate_boilerplate.py", file=sys.stderr)
        return 1 if stale else 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
